//
// Created by Bill on 20/08/2020.
//

#ifndef RAYLIB_GAME_SCENE_CREDITS_H
#define RAYLIB_GAME_SCENE_CREDITS_H

#include "../Engine/Engine.h"

SCENE_METHOD SCENE_CREDITS_Start();
SCENE_METHOD SCENE_CREDITS_Update();
SCENE_METHOD SCENE_CREDITS_Render();
SCENE_METHOD SCENE_CREDITS_Close();


#endif //RAYLIB_GAME_SCENE_CREDITS_H
