//
// Created by Bill on 26/08/2020.
//

#ifndef RAYLIB_GAME_SCENE_WORLDCREATION_H
#define RAYLIB_GAME_SCENE_WORLDCREATION_H

#include "../Engine/Engine.h"

SCENE_METHOD SCENE_WORLD_CREATION_START();
SCENE_METHOD SCENE_WORLD_CREATION_UPDATE();
SCENE_METHOD SCENE_WORLD_CREATION_RENDER();
SCENE_METHOD SCENE_WORLD_CREATION_CLOSE();

typedef struct {
    int x;
} SCENE_WORLD_CREATION_Data;

#endif //RAYLIB_GAME_SCENE_WORLDCREATION_H
