//
// Created by Bill on 21/08/2020.
//

#ifndef RAYLIB_GAME_SCENE_PROCEDURALWORLDMENU_H
#define RAYLIB_GAME_SCENE_PROCEDURALWORLDMENU_H

#include "../Engine/Engine.h"

SCENE_METHOD SCENE_PROCEDURAL_WORLD_MENU_START();
SCENE_METHOD SCENE_PROCEDURAL_WORLD_MENU_UPDATE();
SCENE_METHOD SCENE_PROCEDURAL_WORLD_MENU_RENDER();
SCENE_METHOD SCENE_PROCEDURAL_WORLD_MENU_CLOSE();
typedef struct {
    int cursorHighlight;
    int size;
    int scale;
} SCENE_PROCEDURAL_WORLD_MENU_Data;

#endif //RAYLIB_GAME_SCENE_PROCEDURALWORLDMENU_H
