//
// Created by Bill on 21/08/2020.
//

#ifndef RAYLIB_GAME_SCENE_NEWWORLDMENU_H
#define RAYLIB_GAME_SCENE_NEWWORLDMENU_H

#include "../Engine/Engine.h"

SCENE_METHOD SCENE_NEW_WORLD_MENU_START();
SCENE_METHOD SCENE_NEW_WORLD_MENU_UPDATE();
SCENE_METHOD SCENE_NEW_WORLD_MENU_RENDER();
SCENE_METHOD SCENE_NEW_WORLD_MENU_CLOSE();
typedef struct {
    int cursorHighlight;
} SCENE_NEW_WORLD_MENU_Data;

#endif //RAYLIB_GAME_SCENE_NEWWORLDMENU_H
